# https://taskfile.dev

version: '3'

includes:
  rhash: ./Taskfile/Taskfile-rhash.yml
  rhash-dirs: ./Taskfile/Taskfile-rhash-dirs_{{OS}}.yml

tasks:
  default:
    vars: 
      GREETING: "Welcome to Taskfile. Use -l, -a, --list or --list-all to show all commands"
    desc: "{{.GREETING}}"
    cmds:
      - echo "{{.GREETING}}"
    silent: true